version: '3.8'

services:
  x-api-service: &x-api-service
    build: .
    depends_on:
    - redis
    networks:
      - backend
      - payment-processor
    environment:
      - PAYMENT_PROCESSOR_URL=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0

  backend1:
    <<: *x-api-service
    container_name: backend1
    hostname: backend1

  backend2:
    <<: *x-api-service
    container_name: backend2
    hostname: backend2

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx1
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - backend1
      - backend2
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "70M"
    networks:
      - backend
  
volumes:
  redis_data:
networks:
  backend:
    driver: bridge
  payment-processor:
    external: true